### ISSUE TITLE
Pyramid example app isn't working

### ISSUE THREAD

**Issue by josuemontano** [authomatic/authomatic#189]
Hi,

The pyramid example app isn't working. I get the following error with both Twitter and Google providers:

```
authomatic: Twitter: Reported suppressed exception: AttributeError("'ssl.SSLError' object has no attribute 'message'",)!
```

I'm running python 3.6.2 and pyramid 1.9.1.

**Comment by ysau** [comment]
I have managed to get it to work with Google O-auth 2.0.  See example at https://github.com/ysau/pyramid_google_oauth

**Comment by ergo** [comment]
Pyramid example needs general rework - No idea who wrote it but it is complicated way more than required.
https://github.com/ergo/testscaffold/blob/master/testscaffold/views/auth.py#L59 - i have one that is much smaller here. Maybe we should backport something like that as authomatic examples.

**Comment by mrichar1** [comment]
After several years of inactivity, `authomatic` is now under community management, and we have just released a new stable version (`1.0.0`).

We are now reviewing all issues and PRs and hoping to begin work to solve as many of these as possible.

We are keen to find out which issues still apply, and which PRs are still required/are likely to merge cleanly into the current code. We are aiming to review them all, but any help with prioritisation would be very useful!

If you are still interested in having this issue/PR resolved, or are able to help us work on it, please reply to this message. That way we know which issues are most important to the community.
